fix experimental crash (#1534)
When a a mothercell would try to eject pellets, server would crash due to an undefined reference to Vec2.
Woops, my fault.